import '../globals.css'
import { Inter } from 'next/font/google'
import StoreProvider from '@/store/StoreProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ABRA Test App',
  description: 'Generated by Gavrilov Mikhail',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-slate-100 dark:bg-slate-900`}>
        <StoreProvider>
          <>
            {children}
          </>
        </StoreProvider>
      </body>
    </html>
  )
}
