import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { NextIntlClientProvider } from 'next-intl'
import { notFound } from 'next/navigation'
import CartContextProvider from '@/context/CartContextProvider'

export function generateStaticParams() {
  return [{ locale: 'en' }]
}

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ABRA Test App',
  description: 'Generated by Gavrilov Mikhail',
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: any
}) {
  let messages
  try {
    messages = (await import(`../../messages/${locale}.json`)).default
  } catch (error) {
    notFound()
  }

  return (
    <html lang={locale}>
      <body className={`${inter.className} bg-slate-100 dark:bg-slate-900`}>
        <Navbar />
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
